name: TextboxList
author: rauchg
category: Widgets
tags: [keyboard, facebook, tokenizer, input]
docs: http://devthought.com/projects/mootools/textboxlist/
demo: http://devthought.com/wp-content/project/mootools/textboxlist/Demo/